### PR TITLE
Feature/xcdatamodel

### PR DESCRIPTION
**Pull request by glauberl-ciandt**

### CODE REVIEW

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
sdsdsadsad

**Review by gabriel-kozma-ciandt — APPROVED** [review]

**Comment by glauberl-ciandt** [comment]
aaa

**Comment by jmiguel-cit** [comment]
QA:Tested

**Comment by jmiguel-cit** [comment]
QA:Tested

**Comment by glauberl-ciandt** [comment]
QA:Tested

**Comment by glauberl-ciandt** [comment]
QA testing is not required

**Comment by jmiguel-cit** [comment]
QA:Tested

**Review by aforner — APPROVED** [review]

**Comment by glauberl-ciandt** [comment]
kkkk

**Review by aforner — CHANGES_REQUESTED** [review]
Çerto e errado

**Review by aforner — APPROVED** [review]
No changes

**Review by aforner — CHANGES_REQUESTED** [review]
hjmjm

**Review by aforner — APPROVED** [review]
Gracias gaston

**Review by aforner — CHANGES_REQUESTED** [review]
Dale

**Comment by glauberl-ciandt** [comment]
aaaaa

**Comment by glauberl-ciandt** [comment]
aaaaa

**Comment by glauberl-ciandt** [comment]
aaaaaa

**Comment by glauberl-ciandt** [comment]
aaaaaa

**Comment by glauberl-ciandt** [comment]
aaaaaaa

**Comment by glauberl-ciandt** [comment]
aaaaa

**Comment by glauberl-ciandt** [comment]
aaa

**Review by aforner — APPROVED** [review]
LA pantaja

**Comment by glauberl-ciandt** [comment]
aaaa

**Review by aforner — CHANGES_REQUESTED** [review]
Hablar com mi Equipo

**Review by aforner — CHANGES_REQUESTED** [review]
dffdsfdfdsfs

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
aaaa

**Review by aforner — APPROVED** [review]

**Review by aforner — CHANGES_REQUESTED** [review]
Gracias

**Pull request closed without merging**
