### PR TITLE
Feature/xcdatamodel

### PR DESCRIPTION
**Pull request by glauberl-ciandt**

### CODE REVIEW

**Review by aforner — APPROVED** [review]
çerto

**Comment by gabriel-kozma-ciandt** [comment]
çerto

**Review by gabriel-kozma-ciandt — APPROVED** [review]
go go

**Comment by glauberl-ciandt** [comment]
QA approval is not required

**Comment by glauberl-ciandt** [comment]
teste

**Comment by glauberl-ciandt** [comment]
outro teste

**Comment by glauberl-ciandt** [comment]
ha!

**Comment by glauberl-ciandt** [comment]
opa!

**Comment by glauberl-ciandt** [comment]
e agora?

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
aaaaa

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
aaa

**Comment by glauberl-ciandt** [comment]
aaaa

**Comment by glauberl-ciandt** [comment]
fsdfsdfdsf

**Comment by glauberl-ciandt** [comment]
ssadsadsa

**Comment by glauberl-ciandt** [comment]
aaaaa

**Comment by glauberl-ciandt** [comment]
teste

**Comment by glauberl-ciandt** [comment]
ccvcvcvcvc

**Pull request closed without merging**
